project:
  type: website

website:
  title: "smusings"
  favicon: "favicon.png"
  navbar:
    background: "black"
    foreground: 'white'
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    #theme: cosmo
    theme:
      light: cosmo
      dark: [cosmo, dark-theme.scss]
    css: styles.css

editor: visual

